"""Build the off-repo scratch workspace for an agent run.

Copies the full substrate UE project tree into /tmp/run-agent-<id>/CraftBenchTemplate/
so the user can open it in their UE editor (A2 pre-flight) and the agent's
MCP-mediated edits land in the workspace copy, not the live template.

Two filter lists:

- SKIP_SUBTREES: regenerated by UE on project open, no need to copy.

- HIDDEN_PATHS: substrate paths that MUST NOT be visible to the agent — the
  verifier-only test module (which is hash-pinned and seeing it would leak
  fixture internals) and the sandbox manifest itself. This is NARROWER than
  AGENT_WRITABLE.json's `deny` list, which governs submission-time write
  acceptance (enforced by tools/verify-single/sandbox.py, not here). For
  example: Config/, Content/, Plugins/, and CraftBenchTemplate.uproject are
  all on the substrate's deny list but MUST be copied to the workspace so
  UE can open the project — they're "agent can see, can't write" rather
  than "agent must not see."

Copied files are classified writable/readonly by the VERIFIER'S OWN accept
predicate (``sandbox._is_writable``), narrowed to what THIS TASK may write —
see :func:`_writable_for_task`. PROMPT.md enumerates a documented SUBSET of
that set; see :func:`_render_prompt`.
"""

from __future__ import annotations

import json
import os
import shutil
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional

# The per-task staging classifier is shared with the verifier and the graded
# scratch (same module graded_scratch.py imports) — one source of truth for
# what "foreign task content" means.
_VERIFY_SINGLE = str(Path(__file__).resolve().parents[1] / "verify-single")
if _VERIFY_SINGLE not in sys.path:
    sys.path.insert(0, _VERIFY_SINGLE)
import task_layout  # noqa: E402

# The write-scope rule is the VERIFIER's, not ours. Same delegation snapshot.py
# makes (see its module docstring) and for the same reason: this module used to
# spell the rule as `manifest["writable"]`, which ignores `asset_writable`,
# `config_writable` and `deny` — the sixth copy of a rule five places must agree
# on. Bound BY NAME AT IMPORT TIME on purpose, so a rename in sandbox.py is an
# ImportError every run-agent import sees instead of a silent drift.
#
# NOT imported from snapshot.SubmissionRule (the object run.py uses) only
# because snapshot.py does `from workspace import Workspace` at import time, so
# depending on it here would be a hard cycle. `SubmissionRule.accepts` is itself
# a straight delegation to `_is_writable`, so both sides call the SAME function
# object — they cannot diverge — and `tests/test_submission_rule.py::
# TestManifestParseMatchesTheVerifier` already pins the two loaders equal on
# every committed manifest.
from sandbox import WritableManifest as _WritableManifest  # noqa: E402
from sandbox import _is_writable as _sandbox_is_writable  # noqa: E402
from sandbox import _matches_prefix as _sandbox_matches_prefix  # noqa: E402
from sandbox import _normalize_prefix as _sandbox_normalize_prefix  # noqa: E402

# The per-task config narrowing is preamble.py's, verbatim — it is the module
# that already derives "which Config/ files may THIS TASK touch" from the task's
# own `config_allow`, with the measurement and the fail direction documented on
# the helper. Reusing it (rather than re-deriving the intersection here) is the
# whole point: the prompt contract the preamble renders and the writable listing
# this module renders are the same paragraph of the same PROMPT.md, and they
# must not be able to disagree.
from preamble import _config_files_for_task as _licensed_config_files  # noqa: E402


SKIP_SUBTREES = ("Binaries", "Intermediate", "DerivedDataCache", "Saved")

HIDDEN_PATHS = (
    "Source/CraftBenchTests/",  # verifier-only module, fixture internals leak the answer
    "AGENT_WRITABLE.json",       # sandbox manifest, no reason for the agent to see it
)


@dataclass
class Workspace:
    root: Path                              # /tmp/run-agent-<run-id>/
    project_dir: Path                       # <root>/CraftBenchTemplate/
    prompt_path: Path                       # <root>/PROMPT.md
    writable_files: List[Path] = field(default_factory=list)
    readonly_files: List[Path] = field(default_factory=list)
    # The AGENT_WRITABLE.json `writable` prefixes (substrate-relative) — that ONE
    # manifest key and nothing more. It is NOT the submission rule: snapshot.py
    # re-walks project_dir against the substrate manifest's FULL rule at snapshot
    # time (so agent-CREATED files, and the asset/config lanes, are captured).
    # run.py's two other Workspace constructors carry the same narrow meaning.
    writable_prefixes: List[str] = field(default_factory=list)


def matches_any_prefix(rel_posix: str, prefixes: List[str]) -> bool:
    return any(rel_posix.startswith(p) for p in prefixes)


# Backwards-compatible private alias (used within this module).
_matches_any_prefix = matches_any_prefix


def _licensed_config_files_for(manifest_data: dict, active_task_id: str,
                               substrate_root: Path) -> frozenset:
    """The Config/ files THIS TASK may write, as normalized rel-paths.

    Delegates to ``preamble._config_files_for_task`` — the manifest's
    ``config_writable`` list INTERSECTED with what the task spec's
    ``config_allow`` rules license. Read that helper's docstring for why the
    intersection is the right set and not the manifest list: measured
    2026-08-19, a config edit on a task with no ``config_allow`` fails the
    runner's semantic gate and exits 4 SANDBOX-REJECT for the WHOLE submission,
    and 63 of the 64 ThirdPerson tasks declare none.

    Returns EMPTY without a task id — the ``--workspace`` reuse / ad-hoc-spec
    path, where run.py could not resolve a canonical id. That is the fail-CLOSED
    direction and it is stated rather than assumed: with no task we cannot tell
    "this task licenses no config file" from "we could not find out", so we
    promise nothing, which is exactly the pre-2026-08-19 contract.

    ``repo`` is derived from the substrate root the same way run.py derives it
    for the preamble render (``args.substrate_root.parents[1]``), so the two
    halves of one PROMPT.md read the same repo."""
    if not active_task_id or not manifest_data.get("config_writable"):
        return frozenset()
    try:
        repo = Path(substrate_root).resolve().parents[1]
    except IndexError:                       # substrate root not <repo>/UE-projects/<x>
        return frozenset()
    return frozenset(
        _sandbox_normalize_prefix(f)
        for f in _licensed_config_files(manifest_data, active_task_id, repo)
    )


def _writable_for_task(rel_posix: str, manifest, licensed_config: frozenset) -> bool:
    """Would the verifier accept this rel-path FROM THIS TASK?

    Two stages, mirroring what actually happens at grading time:
      1. ``sandbox._is_writable`` — the path gate (writable prefixes, the
         .uasset/.umap asset lane, the exact-path config lane; deny wins).
      2. the config narrowing — a ``config_writable`` path is only genuinely
         writable when the task's ``config_allow`` covers it; otherwise
         ``config_lane.validate_config_submission`` rejects the run.

    Stage 2 can only ever REMOVE a path stage 1 allowed, so `deny` still wins.
    Doing it the other way round (adding ``config_writable`` to the writable
    listing wholesale) would promise every task both of ThirdPerson's config
    files, and on the 63 that declare no ``config_allow`` a config edit is a
    sandbox-class reject, i.e. a non-graded, unrecoverable cell."""
    allowed, _reason = _sandbox_is_writable(rel_posix, manifest)
    if allowed and rel_posix in manifest.config_writable:
        return rel_posix in licensed_config
    return allowed


def _prompt_enumerates(rel_posix: str, manifest, licensed_config: frozenset) -> bool:
    """Does PROMPT.md name this writable file individually?

    Yes for the SOURCE lane (``writable`` prefixes) and for the task's licensed
    config files. NO for a file writable only through the ``asset_writable``
    lane, and that omission is deliberate and measured (2026-08-19):

      * In a clean checkout the omission covers EXACTLY ZERO files.
        ``git ls-files`` returns 0 tracked files under every asset-lane-only
        prefix of both substrates (Content/Blueprints|Abilities|
        Generated_Materials|Generated_Audio/, and ThirdPerson's two OFPA mirror
        roots Content/__External{Actors,Objects}__/Tasks/). The frozen bench
        tree C:/cb/bench-tree has none of them on disk either.
      * In THIS dev tree those roots hold 144 files — all .uasset, all under the
        OFPA mirrors, all GITIGNORED leftovers of a previous preview run.
        Enumerating them would make PROMPT.md's length depend on gitignored
        dev-box residue: bp/t3-piercing-projectile renders 120 lines, and would
        render 264 here but 120 on a fresh clone of the same commit. Prompt
        length is a fairness lever, so a listing that varies by machine is worse
        than one that is a documented subset.
      * These lanes are for files the agent CREATES, and creation is already
        covered upstream in the same PROMPT.md: tasks/PREAMBLE.md renders
        {asset_roots} from ``asset_writable`` (both OFPA roots included — pinned
        by test_preamble.TestOfpaMirrorRootsReachTheAgent). The listing here is
        "existing files you may edit", which is a different question.

    So the trailing "other files are read-only" instruction is exact on a clean
    checkout and conservative only over gitignored residue nobody should edit.
    ``writable_files`` (the run artifact) is NOT subsetted — it stays equal to
    what the sandbox accepts for the task, so the two never drift apart
    silently."""
    if rel_posix in licensed_config:
        return True
    return any(_sandbox_matches_prefix(rel_posix, p) for p in manifest.writable)


def _is_link_like(p: Path) -> bool:
    """Symlinks AND NTFS junctions; ``Path.is_junction`` is 3.12+ — fall back
    to the lstat reparse tag (Windows-only attr; POSIX links are symlinks)."""
    try:
        if p.is_symlink():
            return True
        is_junc = getattr(p, "is_junction", None)
        if is_junc is not None:
            return bool(is_junc())
        return bool(getattr(os.lstat(p), "st_reparse_tag", 0))
    except OSError:
        return True


def build_workspace(
    substrate_root: Path,
    agent_writable_json: Path,
    prompt_text: str,
    run_id: str,
    root_dir: Optional[Path] = None,
    extra_skip_subtrees: tuple = (),
    active_task_id: str = "",
    task_spec_text: str = "",
) -> Workspace:
    """Build a /tmp/run-agent-<id>/ workspace from substrate_root.

    ``extra_skip_subtrees`` names additional top-level dirs to omit from the
    copy (on top of SKIP_SUBTREES). Baseline backends (claude-p / openrouter)
    pass ``("Plugins",)``: they edit source directly and never open UE, so the
    huge Plugins tree — the host-local aura-plugin clone, which bundles a
    PortablePython whose deep site-packages paths blow past the Windows 260-char
    MAX_PATH on copy — must NOT be copied.

    ``active_task_id`` (with the task's ``task_spec_text``) opts into PER-TASK
    ISOLATION — the same staging the graded scratch applies: foreign per-task
    trees, foreign marker-tagged flat scaffolds, and foreign root-level flat
    maps are pruned from the copy, and the verifier-only ``Tools/`` scaffolder
    dir is skipped entirely. Without it the copy keeps the historical
    everything-but-HIDDEN_PATHS shape (``--workspace`` reuse, ad-hoc builds).

    ``active_task_id`` ALSO gates the config lane: it is what lets us ask which
    Config/ files this task's ``config_allow`` licenses. With no task id we
    cannot tell "licenses none" from "could not find out", so none are promised
    (:func:`_licensed_config_files_for`)."""
    if root_dir is None:
        root_dir = Path(tempfile.gettempdir())
    skip_subtrees = SKIP_SUBTREES + tuple(extra_skip_subtrees)
    if active_task_id:
        # Map scaffolders are verifier-side recipes: they name every task's
        # fixture class + placement in plain text, and no agent needs them.
        skip_subtrees = skip_subtrees + ("Tools",)
    root = root_dir / f"run-agent-{run_id}"
    root.mkdir(parents=True, exist_ok=True)

    project_dir = root / substrate_root.name
    if project_dir.exists():
        shutil.rmtree(project_dir)

    manifest = json.loads(agent_writable_json.read_text(encoding="utf-8"))
    writable_prefixes: List[str] = manifest["writable"]
    # The verifier's own parsed manifest + the task's config narrowing. Both
    # committed manifests carry `substrate`/`game_module`, so `load` is the
    # authoritative parser here; a manifest missing them is a substrate defect
    # and should raise rather than silently parse into a narrower rule.
    rule = _WritableManifest.load(agent_writable_json)
    licensed_config = _licensed_config_files_for(
        manifest, active_task_id, substrate_root)

    writable_files: List[Path] = []
    readonly_files: List[Path] = []
    # The subset PROMPT.md names one by one — see _prompt_enumerates.
    prompt_files: List[Path] = []

    for dirpath, dirnames, filenames in os.walk(substrate_root):
        # NEVER traverse directory junctions/symlinks. They are local-machine
        # artifacts whose targets are huge and whose deep paths blow the Windows
        # 260-char MAX_PATH mid-copy (WinError 3). (Plugins/ is now a real cloned
        # dir, not a junction — baseline backends skip it via skip_subtrees — but
        # this prune stays as a guard against any residual link.) rglob follows
        # junctions; os.walk lets us prune them here.
        dirnames[:] = [
            d for d in dirnames if not _is_link_like(Path(dirpath) / d)
        ]
        for name in sorted(filenames):
            src = Path(dirpath) / name
            rel = src.relative_to(substrate_root)
            rel_posix = rel.as_posix()

            if rel.parts and rel.parts[0] in skip_subtrees:
                continue
            if _matches_any_prefix(rel_posix, HIDDEN_PATHS):
                continue
            # A DANGLING symlink (e.g. the committed Plugins/Aura pointer on a
            # fresh CI checkout, where no real junction masks it) walks as a
            # FILENAME, not a dirname — copying it raises FileNotFoundError.
            # Links are never workspace content; skip them here too.
            if src.is_symlink() or not src.is_file():
                continue

            dst = project_dir / rel
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)

            if _writable_for_task(rel_posix, rule, licensed_config):
                writable_files.append(dst)
                if _prompt_enumerates(rel_posix, rule, licensed_config):
                    prompt_files.append(dst)
            else:
                readonly_files.append(dst)

    if active_task_id:
        # Same per-task staging the graded scratch runs (task_layout is the
        # shared classifier). The copy is disposable, so pruning here can
        # never touch the checkout. Fail-safe direction is KEEP: untagged
        # scaffolds stay, and root maps are kept whenever the spec (a
        # SUPERSET regex over the text) names them.
        task_layout.stage_per_task_dirs_active_only(project_dir, active_task_id)
        task_layout.stage_flat_scaffolds_active_only(project_dir, active_task_id)
        task_layout.stage_root_maps_active_only(
            project_dir, task_layout.spec_map_names(task_spec_text))
        writable_files = [p for p in writable_files if p.exists()]
        readonly_files = [p for p in readonly_files if p.exists()]
        prompt_files = [p for p in prompt_files if p.exists()]

    prompt_path = root / "PROMPT.md"
    prompt_path.write_text(_render_prompt(prompt_text, project_dir, prompt_files),
                           encoding="utf-8")

    return Workspace(
        root=root,
        project_dir=project_dir,
        prompt_path=prompt_path,
        writable_files=writable_files,
        readonly_files=readonly_files,
        writable_prefixes=writable_prefixes,
    )


def _render_prompt(prompt_body: str, project_dir: Path, listed: List[Path]) -> str:
    """PROMPT.md = the task text + the workspace mechanics.

    Behavioral constraints (unattended-run rules, write-scope, disk-truth)
    live in the CENTRAL preamble (tasks/PREAMBLE.md, rendered into
    ``prompt_body`` upstream by prompt_extract) — they are deliberately NOT
    duplicated here. This renderer adds only what is workspace-COPY specific:
    the concrete path, the writable-file listing, and the deliverable
    mechanics. A preamble-led body already opens with its own headings, so
    the legacy "# Your task" wrapper is added only for bare bodies (toy
    repos / specs run without a preamble).

    ``listed`` is the per-task writable set minus the asset-lane-only files
    (:func:`_prompt_enumerates`). The task's licensed Config/ file, when it has
    one, is an ORDINARY ENTRY in this list rather than a section of its own —
    two reasons, both load-bearing:

      * A separate "editable config files" heading would render EMPTY on the 63
        of 64 ThirdPerson tasks with no ``config_allow`` and on every
        CraftBenchTemplate task (that manifest has no ``config_writable`` and
        denies Config/ outright). One list cannot render an empty heading.
      * The EDIT-never-create wording is preamble.py's law (its ``_CONFIG_CLAUSE``:
        "You may also EDIT (never create, never delete) exactly these existing
        files, and nothing else under Config/ is writable"), and that clause is
        already in THIS SAME FILE — the preamble is prepended into
        ``prompt_body`` above. Restating it here would be a second spelling of a
        rule that must not be able to disagree with itself.

    Measured 2026-08-19 on bp/t3-piercing-projectile (ThirdPerson): before this
    change Config/DefaultEngine.ini — a committed reference deliverable that
    sandbox.py path-accepts and the task's ``config_allow`` licenses verbatim —
    was absent from this listing and therefore covered by the trailing "other
    files … are read-only context; do not edit them", contradicting the
    preamble clause 60 lines above it in the same document. Nothing PREVENTED
    the write (build_workspace copies with shutil.copy2 and the file stays
    writable; snapshot.py's collector accepts it), so the cell measured whether
    the model would DISOBEY an explicit written instruction, not whether it
    could do the task."""
    writable_listing = "\n".join(
        f"  - {p.relative_to(project_dir).as_posix()}" for p in listed
    )
    body = prompt_body.strip()
    if not body.startswith("#"):
        body = f"# Your task\n\n{body}"
    return f"""{body}

# Your workspace

Workspace path: {project_dir}

Writable source files (your edits to these are the submission):

{writable_listing}

Other files in this directory are read-only context; do not edit them.
Do not read, list, or run shell commands outside this workspace directory.

Work directly on the files with your Read / Write / Edit / Bash tools.
There is NO running Unreal Editor and NO Unreal MCP tools in this
session — do not wait for or search for them. Verify your change by
reading the code; you may build with UnrealBuildTool via Bash if you
want compile confirmation.

# Deliverable

Your edited writable files are the submission. End your response with
one or two sentences summarizing what you changed.
"""
