"""R2 advisory orchestrator — build the firewalled judge workspace, run the
ensemble, emit a NON-GATING advisory block.

This is the workspace-level half of the firewall: the judge investigates a CLEAN
project built from (substrate ∪ submission) ONLY. The deterministic gate's
report/logs and the author's reference solution are never copied in, so the
judge cannot anchor on them. The verifier-only test module is hidden too (its
fixtures encode the answer key — same reason the agent never sees it).

The model call (``llm_call``) and any UE-backed read-only tools (``ue_tools``)
are injected so the orchestrator is unit-testable with no editor and no API key.
``main()`` wires the live bindings behind deferred imports (a dependency-free
urllib call to the Anthropic API — never Aura, per anti-circularity).

Design intent: judge.py's module docstring (the canonical statement).
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
import tempfile
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional

_HERE = Path(__file__).resolve().parent
if str(_HERE) not in sys.path:
    sys.path.insert(0, str(_HERE))

from config import FIREWALLED_ARTIFACT_NAMES  # noqa: E402
from judge import (  # noqa: E402
    DEFAULT_TOOL_SPECS,
    build_groundtruth_tool,
    build_judge_context,
    build_readonly_fs_tools,
    build_workspace_readonly_tools,
    run_ensemble,
)
from ue_tools import build_editor_introspect_tool  # noqa: E402

# Regenerated by UE on open — never copy into the judge workspace.
_SKIP_SUBTREES = ("Binaries", "Intermediate", "DerivedDataCache", "Saved")
# Paths the JUDGE must not see: the verifier-only fixture module (answer-key
# internals), the sandbox manifest, and any stray deterministic-gate artifact.
_JUDGE_HIDDEN_PREFIXES = (
    "Source/CraftBenchTests/",
    "AGENT_WRITABLE.json",
)


def _hidden(rel_posix: str) -> bool:
    # Case-insensitive: macOS APFS resolves Source/craftbenchtests/ to the real
    # verifier-only module, so the firewall must match regardless of case (#2).
    low = rel_posix.lower()
    if any(low.startswith(p.lower()) for p in _JUDGE_HIDDEN_PREFIXES):
        return True
    # never copy a gate report/verdict artifact, wherever it sits
    return Path(low).name in {n.lower() for n in FIREWALLED_ARTIFACT_NAMES}


def build_judge_workspace(
    substrate_root: Path,
    submission_root: Path,
    run_id: str,
    *,
    root_dir: Optional[Path] = None,
) -> Path:
    """Clone substrate (minus hidden/answer-key paths) and overlay the submission.

    Returns the judge's project directory. Built fresh each run so it can never
    carry a previous run's gate report.
    """
    substrate_root = Path(substrate_root)
    submission_root = Path(submission_root)
    if root_dir is None:
        root_dir = Path(tempfile.gettempdir())
    root = Path(root_dir) / f"r2-judge-{run_id}"
    project_dir = root / substrate_root.name
    if project_dir.exists():
        shutil.rmtree(project_dir)
    project_dir.mkdir(parents=True, exist_ok=True)

    # 1) clean substrate copy
    for src in substrate_root.rglob("*"):
        if not src.is_file():
            continue
        rel = src.relative_to(substrate_root)
        if rel.parts and rel.parts[0] in _SKIP_SUBTREES:
            continue
        if _hidden(rel.as_posix()):
            continue
        dst = project_dir / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)

    # 2) overlay the agent's submission (its edits ARE the thing being judged).
    #    A submission file that lands on a hidden/answer-key path is refused —
    #    a submission cannot smuggle a gate artifact into the judge's view.
    for src in submission_root.rglob("*"):
        if not src.is_file():
            continue
        rel = src.relative_to(submission_root)
        if _hidden(rel.as_posix()):
            raise ValueError(f"submission file lands on a firewalled path: {rel.as_posix()}")
        dst = project_dir / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)

    return project_dir


@dataclass
class R2RunResult:
    advisory: Dict[str, Any]
    out_path: Optional[Path]
    workspace: Path


def run_r2(
    task_md_path: Path,
    submission_root: Path,
    substrate_root: Path,
    *,
    agent_model_id: str,
    evaluator_model_id: str,
    llm_call: Callable[..., Dict[str, Any]],
    ue_tools: Optional[Dict[str, Callable[[Dict[str, Any]], Dict[str, Any]]]] = None,
    ue_root: Optional[Path] = None,
    allow_free_form_introspect: bool = False,
    n: int = 5,
    max_steps: int = 24,
    out_path: Optional[Path] = None,
    root_dir: Optional[Path] = None,
    run_id: Optional[str] = None,
) -> R2RunResult:
    """End-to-end advisory run: workspace → firewalled context → ensemble → JSON.

    ``llm_call`` is the injected model seam (``main`` wires the live one). ``ue_tools``
    optionally supplies the read-only UE primitives (editor_introspect, pie_state_probe);
    when absent the judge runs with the built-in filesystem tools alone.
    """
    task_md_path = Path(task_md_path)
    run_id = run_id or uuid.uuid4().hex[:8]
    task_md = task_md_path.read_text(encoding="utf-8")
    task_id = task_md_path.stem

    workspace = build_judge_workspace(
        substrate_root, submission_root, run_id, root_dir=root_dir
    )

    # The UE introspection tool binds to the freshly-built workspace project.
    # DISABLED BY DEFAULT (#1c): free-form editor_introspect runs arbitrary
    # read-only editor-Python with full FS+network reach — an answer-key
    # exfiltration / anti-circularity vector. Only wire it on explicit opt-in,
    # pending the parameterized read-only query menu (design follow-up B).
    if allow_free_form_introspect and ue_root is not None and ue_tools is None:
        ue_tools = build_editor_introspect_tool(Path(ue_root), workspace)

    # Only expose tools that are actually wired this run (an unwired tool in the
    # menu just wastes judge turns). Filesystem + groundtruth are always wired;
    # the UE editor_introspect tool only when the caller supplies it.
    wired = {"list_submission", "read_submission_file", "workspace_list",
             "workspace_read", "read_task_groundtruth"}
    if allow_free_form_introspect and ue_tools and "editor_introspect" in ue_tools:
        wired.add("editor_introspect")
    tool_specs = tuple(s for s in DEFAULT_TOOL_SPECS if s.name in wired)

    ctx = build_judge_context(
        task_md,
        task_id=task_id,
        submission_root=submission_root,
        workspace_root=workspace,
        agent_model_id=agent_model_id,
        evaluator_model_id=evaluator_model_id,
        tool_specs=tool_specs,
    )

    tools: Dict[str, Callable] = {}
    tools.update(build_readonly_fs_tools(Path(submission_root)))
    tools.update(build_workspace_readonly_tools(workspace))
    tools.update(build_groundtruth_tool(ctx.rubric.score_policy.get("groundtruth_facts", [])))
    if allow_free_form_introspect and ue_tools:
        tools.update(ue_tools)

    advisory, results = run_ensemble(ctx, llm_call, tools, n=n, max_steps=max_steps)

    payload = {
        "schema": "craftbench.r2.advisory/v1",
        "task_id": task_id,
        "rubric_id": ctx.rubric.rubric_id,
        "agent_model_id": agent_model_id,
        "advisory": advisory.to_dict(),
        "judges": [
            {
                "judge_index": r.judge_index,
                "groundedness": r.groundedness,
                "verdicts": [
                    {
                        "criterion_id": v.criterion_id,
                        "verdict_label": v.verdict_label,
                        "points": v.points,
                        "grounded": v.grounded,
                        "rationale": v.rationale,
                        "cited_evidence_ids": v.cited_evidence_ids,
                    }
                    for v in r.verdicts
                ],
                "evidence_ids": r.evidence.ids(),
            }
            for r in results
        ],
    }

    if out_path is not None:
        out_path = Path(out_path)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    return R2RunResult(advisory=payload, out_path=out_path, workspace=workspace)


# --------------------------------------------------------------------------- #
# Live model binding — deferred, dependency-free, NEVER imports Aura.
# --------------------------------------------------------------------------- #
def make_anthropic_llm_call(api_key: str, model: str, max_tokens: int = 1500) -> Callable[..., Dict[str, Any]]:
    """A judge ``llm_call`` backed by the Anthropic Messages API via urllib.

    The model is instructed (by judge._judge_system_prompt) to emit exactly one
    JSON object per turn; we parse the first balanced object from its text reply.
    No SDK dependency, no Aura — keeps tools/verify-r2 anti-circular.
    """
    import ssl
    import time as _time
    import urllib.request  # deferred — unit tests inject their own llm_call

    # macOS Python.framework lacks the system CA bundle; prefer certifi so the
    # HTTPS call to api.anthropic.com verifies (same fix as tools/scripts/aura_agent.py).
    try:
        import certifi
        _ssl_ctx = ssl.create_default_context(cafile=certifi.where())
    except Exception:  # noqa: BLE001
        _ssl_ctx = ssl.create_default_context()

    def _first_json_object(text: str) -> Dict[str, Any]:
        # String-aware brace scan: braces inside JSON string literals (e.g. a
        # rationale mentioning "{}") must not throw off the depth count. Returns
        # the first balanced top-level object, ignoring any prose around it.
        depth = 0
        start = -1
        in_str = False
        esc = False
        for i, ch in enumerate(text):
            if in_str:
                if esc:
                    esc = False
                elif ch == "\\":
                    esc = True
                elif ch == '"':
                    in_str = False
                continue
            if ch == '"':
                in_str = True
            elif ch == "{":
                if depth == 0:
                    start = i
                depth += 1
            elif ch == "}" and depth > 0:
                depth -= 1
                if depth == 0 and start != -1:
                    try:
                        return json.loads(text[start:i + 1])
                    except json.JSONDecodeError:
                        start = -1
        return {"type": "noop"}

    def _call(*, system, messages, tools, judge_index):
        body = {
            "model": model,
            "max_tokens": max_tokens,
            "system": system,
            "messages": [
                {"role": m.get("role", "user"), "content": str(m.get("content", ""))}
                for m in messages
            ],
        }
        req = urllib.request.Request(
            "https://api.anthropic.com/v1/messages",
            data=json.dumps(body).encode("utf-8"),
            headers={
                "content-type": "application/json",
                "x-api-key": api_key,
                "anthropic-version": "2023-06-01",
            },
            method="POST",
        )
        # Retry transient API errors (429/5xx/network) with backoff. On persistent
        # failure, abstain THIS judge cleanly — a per-judge hiccup must not crash
        # the whole ensemble (the others still produce a usable advisory).
        last_err = None
        for attempt in range(3):
            try:
                with urllib.request.urlopen(req, timeout=120, context=_ssl_ctx) as resp:  # noqa: S310
                    data = json.loads(resp.read().decode("utf-8"))
                text = "".join(b.get("text", "") for b in data.get("content", []) if b.get("type") == "text")
                return _first_json_object(text)
            except Exception as e:  # noqa: BLE001
                last_err = e
                _time.sleep(2 * (attempt + 1))
        return {"type": "final", "verdicts": [], "_error": f"llm_call failed: {last_err}"}

    return _call


def main(argv: Optional[List[str]] = None) -> int:
    ap = argparse.ArgumentParser(description="Run the R2 advisory judge ensemble.")
    ap.add_argument("--task", required=True, type=Path)
    ap.add_argument("--submission", required=True, type=Path)
    ap.add_argument("--substrate", required=True, type=Path)
    ap.add_argument("--agent-model", required=True, help="agent-under-test model id (firewall: must differ from --eval-model)")
    ap.add_argument("--eval-model", required=True, help="judge model id, e.g. claude-opus-4-8")
    ap.add_argument("--api-model", default="claude-opus-4-8", help="Anthropic API model name for the judge call")
    ap.add_argument("--ue-root", type=Path, default=None,
                    help="UE 5.7 root — only used with --unsafe-free-form-introspect. "
                         "Omit for prose/structure tasks the judge grounds via filesystem alone.")
    ap.add_argument("--unsafe-free-form-introspect", action="store_true",
                    help="DANGER: wire the free-form editor_introspect tool (arbitrary read-only "
                         "editor-Python). DISABLED by default — it can read outside the workspace / "
                         "reach the network (answer-key exfil + anti-circularity risk). Pending the "
                         "parameterized query menu. Only for trusted local runs.")
    ap.add_argument("-n", "--ensemble", type=int, default=5)
    ap.add_argument("--out", type=Path, default=None)
    args = ap.parse_args(argv)

    import os
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("ERROR: ANTHROPIC_API_KEY not set", file=sys.stderr)
        return 2

    llm_call = make_anthropic_llm_call(api_key, args.api_model)
    res = run_r2(
        args.task, args.submission, args.substrate,
        agent_model_id=args.agent_model, evaluator_model_id=args.eval_model,
        llm_call=llm_call, ue_root=args.ue_root,
        allow_free_form_introspect=args.unsafe_free_form_introspect,
        n=args.ensemble, out_path=args.out,
    )
    adv = res.advisory["advisory"]
    print(json.dumps({
        "task_id": res.advisory["task_id"],
        "advisory_score": adv["advisory_score"],
        "confidence": adv["confidence"],
        "gating": adv["gating"],
        "reliability_flags": adv["reliability_flags"],
        "out": str(res.out_path) if res.out_path else None,
    }, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
